[workspace]
resolver = "2"

members = ["client"]

[profile.release]
lto = true
strip = false
opt-level = 3
panic = "abort"
codegen-units = 1

[profile.profiling]
inherits = "release"
debug = true
strip = false
